# Generated by Django 4.2.6 on 2023-10-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
