# Generated by Django 4.2.6 on 2023-10-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_user', '0004_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
