# Generated by Django 4.2.6 on 2023-10-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_user', '0005_remove_user_is_admin_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
